### ISSUE TITLE
DrawingsLoader can't find drawing classes on distribution

### ISSUE THREAD

**Issue by diorge** [lucasdavid/CG-Assignment-1#2]
Although the drawings are found when running directly on IDE, when compiled to distribution the loader cannot find any of the drawing classes.

**Comment by lucasdavid** [comment]
I've just deployed to check this and I noticed that though I can't really see the list of **draw modes** in the left-upper corner, I can still draw lines. When you said "cannot find", you mean its the same cosmetic problem I'm having or that you can't draw anything at all?

**Comment by diorge** [comment]
Lines are still drawable since they are selected by default, other shapes are not.

**Comment by lucasdavid** [comment]
It's fixed for me. Do you mind giving it a try? Also, I'm ready to submit the code, if you don't have any objections.
